#!/bin/sh

set -e

# node_version="$1"

# if [ "$node_version" == "" ]; then
#   echo "usage: $0 VERSION"
#   exit 1
# fi

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t nginx_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# download and extract nginx
curl http://nginx.org/download/nginx-1.0.11.tar.gz -o nginx.tgz
tar xzvf nginx.tgz

# download and extract pcre into contrib directory
pushd nginx-1.0.11/contrib
curl ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.21.tar.gz -o pcre.tgz
tar zvxf pcre.tgz
popd

# build and package nginx for heroku
vulcan build -v -s nginx-1.0.11 -o $tempdir/nginx-1.0.11-heroku.tar.gz -p /app/vendor/nginx -c './configure --prefix=/app/vendor/nginx --with-pcre=contrib/pcre-8.21 --with-http_ssl_module --with-http_gzip_static_module && make install' 

# upload to s3
$basedir/aws/s3 put $S3_BUCKET nginx-1.0.11-heroku.tar.gz $tempdir/nginx-1.0.11-heroku.tar.gz
