#!/bin/sh

set -e

if [ "$PHP_VERSION" == "" ]; then
  echo "must set PHP_VERSION, i.e PHP_VERSION=5.4.1"
  exit 1
fi

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID, i.e. export AWS_ID=1BHAJK48DJFMQKZMNV93"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET, i.e. export AWS_SECRET=fj2jjchebsjksmMJCN387RHNjdnddNfi4jjhshh3"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET, i.e. S3_BUCKET=heroku-buildpack-wordpress"
  exit 1
fi

if [ "$HEROKU_APP" == "" ]; then
  echo "must set HEROKU_APP, i.e. HEROKU_APP=my-octopus"
  exit 1
fi

# download and extract php
# build and package php for heroku
# upload to s3
heroku run --app $HEROKU_APP \
   "mkdir /tmp/aws; \
    curl -L https://raw.github.com/mchung/heroku-buildpack-wordpress/master/support/aws/s3 -o /tmp/aws/s3; \
    curl -L https://raw.github.com/mchung/heroku-buildpack-wordpress/master/support/aws/hmac -o /tmp/aws/hmac; \
    chmod 755 /tmp/aws/s3 /tmp/aws/hmac; \
    rm -rf /app/vendor/php; \
    curl -L http://us.php.net/get/php-$PHP_VERSION.tar.bz2/from/www.php.net/mirror -o /tmp/php.tar.bz2; \
    cd /tmp ; \
    tar xvjf php.tar.bz2; \
    cd php-$PHP_VERSION; \
    ./configure  --prefix=/app/vendor/php \
                --with-mysql \
                --with-pdo-mysql \
                --with-iconv \
                --with-gd \
                --with-curl=/usr/lib \
                --with-config-file-path=/app/vendor/php \
                --with-openssl \
                --enable-fpm \
                --with-zlib \
                --enable-mbstring \
                --disable-debug \
                --disable-rpath \
                --enable-gd-native-ttf \
                --enable-inline-optimization \
                --with-bz2 \
                --enable-pcntl \
                --enable-mbregex \
                --with-mhash \
                --enable-zip \
                --with-pcre-regex \
                --enable-libxml \
                --with-gettext \
                --with-jpeg-dir \
                --with-mysqli \
                --with-pcre-regex \
                --with-png-dir \
                --without-pdo-sqlite \
                --without-sqlite3 \
                && make install \
                && /app/vendor/php/bin/pear config-set php_dir /app/vendor/php \
                && yes '' | /app/vendor/php/bin/pecl install memcache ; \
    cd /app/vendor/php; \
    tar cvfz /tmp/php-$PHP_VERSION-with-fpm-heroku.tar.gz . ; \
    cd /tmp/; \
    aws/s3 put $S3_BUCKET php-$PHP_VERSION-with-fpm-heroku.tar.gz /tmp/php-$PHP_VERSION-with-fpm-heroku.tar.gz"
